[package]
name = "l15_ctrl_c"
version = "0.1.0"
edition = "2021"

[dependencies]
flume = "0.11.0"

[dependencies.tokio]
version = "1.40.0"
features = ["rt-multi-thread", "macros", "signal", "sync", "time"]
